version: 0.1.0.{build}
configuration: Release
platform: x64

branches:
  only:
    - develop
    - master

skip_branch_with_pr: true

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      job_depends_on: Linux
      job_name: Windows

matrix:
  fast_finish: true

install:
  - git clone -q --branch=platform https://github.com/lintest/tools1c.git bin
  - cd bin
  - 7z x tools1c.part01.rar -p%KEY_1CV8T%
  - cd ..

  - git submodule update --init --recursive
  - cd tesseract
  - msbuild tesseract.sln /p:Configuration=Release /p:Platform=x64 /m
  - msbuild tesseract.sln /p:Configuration=Release /p:Platform=x86 /m
  - cd ..

init:
  - cmd: cmake --version
  - cmd: msbuild /version
  - cmd: echo.

build_script:
  - powershell -File manifest.ps1
  - mkdir build32
  - cd build32
  - cmake .. -A Win32 -DMySuffix2=32
  - cmake --build . --config Release --target %APPVEYOR_PROJECT_NAME%
  - cd ..

  - mkdir build64
  - cd build64
  - cmake .. -A x64 -DMySuffix2=64
  - cmake --build . --config Release --target %APPVEYOR_PROJECT_NAME%
  - cd ..

for:
  - matrix:
      only:
        - job_name: Windows

    after_build:
      - copy bin32\Release\%APPVEYOR_PROJECT_NAME%Win32.dll .
      - copy bin64\Release\%APPVEYOR_PROJECT_NAME%Win64.dll .
      - powershell -File appveyor.ps1
      - appveyor PushArtifact AddIn.zip
      - mkdir database
      - bin\1cv8t.exe CREATEINFOBASE File=%CD%/database
      - bin\1cv8t.exe DESIGNER /F %CD%/database /LoadConfigFromFiles %CD%/Config /UpdateDBCfg
      - bin\1cv8t.exe DESIGNER /F %CD%/database /LoadExternalDataProcessorOrReportFromFiles Example.xml %APPVEYOR_PROJECT_NAME%.epf /Out example.log
      - appveyor PushArtifact %APPVEYOR_PROJECT_NAME%.epf
      - bin\1cv8ct.exe ENTERPRISE /LRU /F %CD%/database /Execute %APPVEYOR_PROJECT_NAME%.epf /C install
      - bin\1cv8ct.exe ENTERPRISE /LRU /F %CD%/database /Execute %APPVEYOR_PROJECT_NAME%.epf /C autotest
      - ps: if (!(Test-Path success.txt)) { throw "Имеются ошибки" }

    artifacts:
      - path: AddIn.zip
      - path: ${APPVEYOR_PROJECT_NAME}.epf
      - path: autotest.log
      - path: example.log

    environment:
      KEY_1CV8T:
        secure: OolAVEKkEg1cGCpG/VK2FaM0LWrPgMR/Kn4nTLYyKR0=

    deploy:
      - provider: GitHub
        auth_token:
          secure: v7P89NQ2I5+WGNNdhpFrZEt6OCTPf8A8VSC5rttZMXh3DJ2fTChNEjZ1Wvm3kfBt
        repository: ${APPVEYOR_ACCOUNT_NAME}/${APPVEYOR_PROJECT_NAME}
        artifact: AddIn.zip, ${APPVEYOR_PROJECT_NAME}.epf
        draft: true
        prerelease: true
        force_update: true
        on:
          branch: master
